"""empty message

Revision ID: d8687b17da26
Revises: 07138e236c25
Create Date: 2021-06-13 19:10:47.116418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8687b17da26'
down_revision = '07138e236c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_entrega', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(length=1500), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tarea', sa.Integer(), nullable=True),
    sa.Column('id_alumno', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_tarea'], ['tarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificaciones')
    op.drop_table('tarea')
    # ### end Alembic commands ###
